FROM python:3.10-slim
WORKDIR /code
COPY ../.. /code
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
CMD ["streamlit", "run", "app/frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
